spring.application.name=myapp

# datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/exam_platform_db
spring.datasource.username=root
spring.datasource.password=1234
# session persistence
server.servlet.session.persistent=false

spring.jpa.open-in-view=false

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# logging
logging.level.root=info
logging.level.com.mycom.myapp=debug
logging.level.org.springframework.security=debug

# JWT Secret Key
myapp.jwt.secret=asdf83sdfsdfasdfasdfefdfdfasr3r3efasfasdfASF43QW4A